# Solo mirará los controladores dentro de ese paquete
springdoc.packages-to-scan=com.test.mi_negocio.infraestructure.web.Controllers
spring.devtools.restart.enabled=false

# Solo documentará las rutas que empiecen por /api
springdoc.paths-to-match=/api/**

logging.level.org.springdoc=DEBUG
logging.level.org.springdoc.core=DEBUG
logging.level.org.springframework.web=DEBUG


spring.application.name=mi-negocio
# Datos de conexión PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mi_negocio
spring.datasource.username=postgres
spring.datasource.password=Guakatul@1
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
