spring.application.name=mi-negocio
# Datos de conexión PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mi_negocio
spring.datasource.username=postgres
spring.datasource.password=Guakatul@1
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
